exports.REGULAR_CAMPAIGN_TYPES_ENUM = {
    REPEATED_MONTHLY: 'REGULAR_REPEATED_MONTHLY',
    REPEATED_WEEKLY: 'REGULAR_REPEATED_WEEKLY',
};

exports.IRREGULAR_CAMPAIGN_TYPES_ENUM = {
    EVENT: 'EVENT',
};
