exports.REGULAR_CAMPAIGN_TYPES_ENUM = {
    REPEATED_DAILY: 'REGULAR_REPEATED_DAILY',
    REPEATED_WEEKLY: 'REGULAR_REPEATED_WEEKLY',
    REPEATED_MONTHLY: 'REGULAR_REPEATED_MONTHLY',
};

exports.IRREGULAR_CAMPAIGN_TYPES_ENUM = {
    EVENT: 'EVENT',
};

exports.SOCIAL_MEDIA_PLATFORMS = {
    FACEBOOK: 'FACEBOOK',
    INSTAGRAM: 'INSTAGRAM',
    TWITTER: 'TWITTER',
};
